name: Publish package at midnight everyday

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  main:
    if: github.repository_owner == 'felvin-search'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
          always-auth: true
      - run: yarn install
      - run: |
          chmod +x ./.github/workflows/check-release.sh
          ./.github/workflows/check-release.sh
      - run: yarn build-packages
      - run: yarn publish-packages
        env:
          YARN_NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
